[tool.poetry]
name = "mock-server"
version = "1.0.0"
description = "mock-server for front-end development"
authors = ["punkyoon <cryptography@konkuk.ac.kr>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.20.1"
uvicorn = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
